PetForum/PetForum.Mvc/Controllers/AuthController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetForum.Service.DTOs.User;
using PetForum.Service.Services.Contracts;
using PetForum.Web.Mvc.Helpers;
using PetForum.Web.Mvc.Models;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PetForum.Web.Mvc.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService userService;
        private readonly IMapper mapper;
        private readonly IAuthHelper authHelper;

        public AuthController(IUserService userService, IMapper mapper, IAuthHelper authHelper)
        {
            this.userService = userService;
            this.mapper = mapper;
            this.authHelper = authHelper;
        }

        [HttpGet]
        public IActionResult Login()
        {
            var model = new LogInViewModel();
            return View("Login", model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LogInViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View("Login", model);
            }

            var user = await this.authHelper.TryGetUser(model.Email, model.Password);

            if (user != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim(ClaimTypes.Name, $"{user.FirstName} {user.LastName}"),
                    new Claim(ClaimTypes.Role, user.Role)
                };

                var claimsIdentity = new ClaimsIdentity(claims, "LogIn");

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                                            new ClaimsPrincipal(claimsIdentity));

                return this.RedirectToAction("Index", "Home");
            }

            return this.View(model);
        }

        [HttpGet]
        public IActionResult Register()
        {
            var vm = new CreateUserViewModel();
            return View("Register", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Register(CreateUserViewModel viewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View("Register", viewModel);
            }

            var input = this.mapper.Map<CreateUserDto>(viewModel);
            await this.userService.CreateUserAsync(input);

            return RedirectToAction("Index", "Home");

        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await this.HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);  //?

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> CheckIfUsernameAvailable(string username)
        {
            var user = await this.userService.GetUserByUsernameAsync(username);
            if (user == null)
            {
                return Json("available");
            }
            else
            {
                return Json("unavailable");
            }
        }
    }
}

PetForum/PetForum.Mvc/Controllers/PostController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetForum.Data.Database;
using PetForum.Service.DTOs;
using PetForum.Service.DTOs.User;
using PetForum.Service.Services;
using PetForum.Service.Services.Contracts;
using PetForum.Web.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PetForum.Web.Mvc.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly ICommentService commentService;
        private readonly IMapper mapper;
        private readonly PetForumContext context;

        public PostController(IUserService userService, IPostService postService, ICommentService commentService, IMapper mapper, PetForumContext context)
        {
            this.userService = userService;
            this.postService = postService;
            this.commentService = commentService;
            this.mapper = mapper;
            this.context = context;
        }

        public async Task<IActionResult> Details(int id)
        {
            var post = await postService.GetPostByIdAsync(id);
            var view = this.mapper.Map<PostViewModel>(post);
            return View("Details", view);
        }

        [HttpGet]
        public ActionResult Search()
        {
            return View(new SearchViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Search(SearchViewModel model)
        {
            try
            {
                if (model.SelectedCriteria.ToLower() == "users")
                {
                    List<GetUserDto> users = new List<GetUserDto>();

                    if (model.Keyword == null)
                    {
                        var allUsers = await this.userService.GetAllUsersAsync();
                        users = allUsers.OrderBy(u => u.DisplayName).ToList();
                    }
                    else
                    {
                        var searchedUsers = await this.userService.GetUserByUsernameAsync(model.Keyword);
                    }

                    var searchModel = new SearchViewModel
                    {
                        Users = users
                                   .Select(this.mapper.Map<UserSearchViewModel>)
                                   .ToList()
                    };

                    return View(searchModel);
                }
                else if (model.SelectedCriteria.ToLower() == "posts")
                {
                    var allPosts = await this.postService.GetPostByContentAsync(model.Keyword);

                    var searchModel = new SearchViewModel
                    {
                        Posts = allPosts
                              .Select(this.mapper.Map<PostViewModel>)
                              .ToList()
                    };

                    return View(searchModel);
                }
            }
            catch 
            {
                return RedirectToAction("Search");
            }

            return Ok();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreatePostViewModel();
            return View("Create",viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostViewModel postViewModel)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            postViewModel.UserId = int.Parse(userId); 

            try
            {
                var view = this.mapper.Map<CreatePostDto>(postViewModel, opt => 
                opt.AfterMap((src, dest) => dest.CategoryType = postViewModel.CategoryName)); 
                await this.postService.CreatePostAsync(view);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> PostsCount()
        {
            int count = await this.postService.GetPostsCount();
            var input = new PostViewModel();
            input.PostsCount = count;

            return this.View(input);
        }
    }   
}   

PetForum/PetForum.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - PetForum.Mvc</title>
    <meta charset="utf-8">
    <title>Forum - Responsive HTML5 Template</title>
    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="Forum - Responsive HTML5 Template">
    <meta name="author" content="Forum">
    <link rel="shortcut icon" href="favicon/favicon.ico">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>

    <nav class="panel-menu" id="mobile-menu">
        <ul>
        </ul>
        <div class="mm-navbtn-names">
            <div class="mm-closebtn">
                Close
                <div class="tt-icon">
                    <svg>
                        <use xlink:href="#icon-cancel"></use>
                    </svg>
                </div>
            </div>
            <div class="mm-backbtn">Back</div>
        </div>
    </nav>
    <header id="tt-header">
        <div class="container">
            <div class="row tt-row no-gutters">
                <div class="col-auto">
                    <!-- toggle mobile menu -->
                    <a class="toggle-mobile-menu" href="#">
                        <svg class="tt-icon">
                            <use xlink:href="#icon-menu_icon"></use>
                        </svg>
                    </a>
                    <!-- /toggle mobile menu -->
                    <!-- logo -->
                    <div class="tt-logo">
                        <a href="index.html"><img src="~/images/logo.png" alt=""></a>
                    </div>
                    <!-- /logo -->
                    <!-- desctop menu -->
                    <div class="tt-desktop-menu">
                        <nav>
                            <ul>                        
                                <li>
                                    <a href="page-create-topic.html"><span>Post</span></a>
                                    <ul>
                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            <li><a asp-controller="Post" asp-action="Create">New Post</a></li>
                                        }
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <!-- /desctop menu -->
                    <!-- tt-search -->
                    <div class="tt-search">
                        <!-- toggle -->
                        <button class="tt-search-toggle" data-toggle="modal" data-target="#modalAdvancedSearch">
                            <svg class="tt-icon">
                                <use xlink:href="#icon-search"></use>
                            </svg>
                        </button>
                        <!-- /toggle -->
                        <form class="search-wrapper">
                            <div class="search-form">
                                <input type="text" class="tt-search__input" placeholder="Search" id="index-post-keyword">
                                <a class="tt-search__btn" onclick="searchEventHandler()">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-search"></use>
                                    </svg>
                                </a>
                                <button class="tt-search__close">
                                    <svg class="tt-icon">
                                        <use xlink:href="#cancel"></use>
                                    </svg>
                                </button>
                            </div>
                            <div class="search-results">
                                <div class="tt-search-scroll">
                                    <ul>
                                        <li>
                                            <a href="page-single-topic.html">
                                                <h6 class="tt-title">Rdr2 secret easter eggs</h6>
                                                <div class="tt-description">
                                                    Here’s what I’ve found in Red Dead Redem..
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="page-single-topic.html">
                                                <h6 class="tt-title">Top 10 easter eggs in Red Dead Rede..</h6>
                                                <div class="tt-description">
                                                    You can find these easter eggs in Red Dea..
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="page-single-topic.html">
                                                <h6 class="tt-title">Red Dead Redemtion: Arthur Morgan..</h6>
                                                <div class="tt-description">
                                                    Here’s what I’ve found in Red Dead Redem..
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="page-single-topic.html">
                                                <h6 class="tt-title">Rdr2 secret easter eggs</h6>
                                                <div class="tt-description">
                                                    Here’s what I’ve found in Red Dead Redem..
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="page-single-topic.html">
                                                <h6 class="tt-title">Top 10 easter eggs in Red Dead Rede..</h6>
                                                <div class="tt-description">
                                                    You can find these easter eggs in Red Dea..
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="page-single-topic.html">
                                                <h6 class="tt-title">Red Dead Redemtion: Arthur Morgan..</h6>
                                                <div class="tt-description">
                                                    Here’s what I’ve found in Red Dead Redem..
                                                </div>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <button type="button" class="tt-view-all" data-toggle="modal" data-target="#modalAdvancedSearch">Advanced Search</button>
                            </div>
                        </form>
                    </div>
                    <!-- /tt-search -->
                </div>
                <div class="col-auto ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="tt-account-btn">
                            <a class="btn btn-primary" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </div>
                            <span> @(User.Identity.Name)</span>
                    }
                    else
                    {
                        <div class="tt-account-btn">
                        <a class="btn btn-primary" asp-controller="Auth" asp-action="Login">Login</a>
                        <a class="btn btn-primary" asp-controller="Auth" asp-action="Register">Register</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main id="tt-pageContent" class="tt-offset-small">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PetForum.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/bundle.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>