PetForum/PetForum.Mvc/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PetForum.Web.Mvc.Models
{
    public class PostViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public int UserId { get; set; }

        public string DisplayName { get; set; }

        public int CategoryId { get; set; }

        public DateTime CreatedOn { get; set; }

        public bool IsLiked { get; set; }

        public int PostsCount { get; set; }

        public string NewComment { get; set; }

        public ICollection<PostLikeViewModel> Likes { get; set; } = new List<PostLikeViewModel>();

        public ICollection<CommentViewModel> Comments { get; set; } = new List<CommentViewModel>();
    }
}

PetForum/PetForum.Mvc/Controllers/CommentController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetForum.Service.DTOs;
using PetForum.Service.DTOs.Comment;
using PetForum.Service.Services;
using PetForum.Service.Services.Contracts;
using PetForum.Web.Mvc.Models;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PetForum.Web.Mvc.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService commentService;
        private readonly IPostService postService;
        private readonly IMapper mapper;

        public CommentController(ICommentService commentService, IPostService postService, IMapper mapper)
        {
            this.commentService = commentService;
            this.postService = postService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var comments = await this.commentService.GetAllCommentsAsync();

            var viewModel = this.mapper.Map<CommentViewModel>(comments);

            return View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var comment = await this.commentService.GetCommentByIdAsync(id);

            if (comment == null)
            {
                return NotFound();
            }

            var viewModel = this.mapper.Map<CommentViewModel>(comment);

            return View(viewModel);
        }

        public ActionResult Create()
        {
            var comment = new CreateCommentViewModel();

            return View(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostViewModel viewModel)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            await this.commentService.CreateCommentAsync(viewModel.Id, int.Parse(userId), viewModel.NewComment);

            return this.RedirectToAction("Details", "Post", new { id = viewModel.Id });
        }

        public async Task<IActionResult> Edit(int id, string content)
        {
            var view = new UpdateCommentViewModel();
            view.Id = id;
            view.Content = content;

            return this.View(view);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UpdateCommentViewModel viewModel)
        {
            try
            {
                var map = this.mapper.Map<UpdateCommentDto>(viewModel);

                var model = await this.commentService.UpdateCommentAsync(id, map);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(viewModel);
            }
        }
        public IActionResult Delete(int id, CommentViewModel viewModel)
        {
            try
            {
                var parcel = this.commentService.DeleteCommentAsync(id); 

                var view = this.mapper.Map<CreateCommentDto>(parcel);

                return this.View(view);
            }
            catch (ArgumentException )
            {
                return this.CommentNotFound(id);
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                this.commentService.DeleteCommentAsync(id);
            }
            catch (ArgumentException)
            {
                return this.CommentNotFound(id);
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        private IActionResult CommentNotFound(int id)
        {
            this.Response.StatusCode = StatusCodes.Status404NotFound;
            this.ViewData["error"] = $"Comment with id: {id} does not exist.";
            return this.View("Error");
        }
    }
}

PetForum/PetForum.Mvc/Controllers/PostController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetForum.Data.Database;
using PetForum.Service.DTOs;
using PetForum.Service.DTOs.User;
using PetForum.Service.Services;
using PetForum.Service.Services.Contracts;
using PetForum.Web.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PetForum.Web.Mvc.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly ICommentService commentService;
        private readonly IMapper mapper;
        private readonly PetForumContext context;

        public PostController(IUserService userService, IPostService postService, ICommentService commentService, IMapper mapper, PetForumContext context)
        {
            this.userService = userService;
            this.postService = postService;
            this.commentService = commentService;
            this.mapper = mapper;
            this.context = context;
        }

        public async Task<IActionResult> Details(int id)
        {
            var post = await postService.GetPostByIdAsync(id);
            var view = this.mapper.Map<PostViewModel>(post);
            return View("Details", view);
        }

        [HttpGet]
        public ActionResult Search()
        {
            return View(new SearchViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Search(SearchViewModel model)
        {
            try
            {
                if (model.SelectedCriteria.ToLower() == "users")
                {
                    List<GetUserDto> users = new List<GetUserDto>();

                    if (model.Keyword == null)
                    {
                        var allUsers = await this.userService.GetAllUsersAsync();
                        users = allUsers.OrderBy(u => u.DisplayName).ToList();
                    }
                    else
                    {
                        var searchedUsers = await this.userService.GetUserByUsernameAsync(model.Keyword);
                    }

                    var searchModel = new SearchViewModel
                    {
                        Users = users
                                   .Select(this.mapper.Map<UserSearchViewModel>)
                                   .ToList()
                    };

                    return View(searchModel);
                }
                else if (model.SelectedCriteria.ToLower() == "posts")
                {
                    var allPosts = await this.postService.GetPostByContentAsync(model.Keyword);

                    var searchModel = new SearchViewModel
                    {
                        Posts = allPosts
                              .Select(this.mapper.Map<PostViewModel>)
                              .ToList()
                    };

                    return View(searchModel);
                }
            }
            catch 
            {
                return RedirectToAction("Search");
            }

            return Ok();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreatePostViewModel();
            return View("Create",viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostViewModel postViewModel)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            postViewModel.UserId = int.Parse(userId); 

            try
            {
                var view = this.mapper.Map<CreatePostDto>(postViewModel, opt => 
                opt.AfterMap((src, dest) => dest.CategoryType = postViewModel.CategoryName)); 
                await this.postService.CreatePostAsync(view);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> PostsCount()
        {
            int count = await this.postService.GetPostsCount();
            var input = new PostViewModel();
            input.PostsCount = count;

            return this.View(input);
        }
    }   
}   

PetForum/PetForum.Mvc/Views/Post/Create.cshtml
@model PetForum.Web.Mvc.Models.CreatePostViewModel

<div class="container">
    <div class="tt-wrapper-inner">
        <h1 class="tt-title-border">Create New Topic</h1>
        <form class="form-default" role="form" method="post" asp-action="Create" asp-controller="Post">
            <div class="form-group">
                <label for="inputTopicTitle">Post Title</label>
                <div class="tt-value-wrapper">
                    <input type="text" asp-for="@Model.Title" class="form-control" id="inputTopicTitle" placeholder="Subject of your topic">
                    <span class="tt-value-input">99</span>
                </div>
                <div class="tt-note">Describe your post well, while keeping the subject as short as possible.</div>
            </div>
            <div class="pt-editor">
                <h6 class="pt-title">Post Content</h6>               
                <div class="form-group">
                    <textarea type="text" asp-for="@Model.Content" class="form-control" rows="5" placeholder="Lets get started"></textarea>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="inputTopicTitle">Category</label>
                            <select asp-for="@Model.CategoryName" asp-items="@Model.Categories" class="form-control">
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-auto ml-md-auto">
                        <div class="form-group">
                            <button type="submit" class="btn btn-secondary btn-block">Create Post</button>&nbsp;
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

PetForum/PetForum.Mvc/Views/Post/Details.cshtml
@model PetForum.Web.Mvc.Models.PostViewModel

<div class="container">
    <div class="tt-single-topic-list">
        <div class="tt-item">
            <div class="tt-single-topic">
                <form class="form-default" role="form" method="get" asp-action="Details" asp-controller="Post">
                    <div class="tt-item">
                        <div class="tt-single-topic">
                            <div class="tt-item-header">
                                <div class="tt-item-info info-top">
                                    <div class="tt-avatar-icon">
                                        <i class="tt-icon"><svg><use xlink:href="#icon-ava-d"></use></svg></i>
                                    </div>
                                    <div class="tt-avatar-title">
                                        <a href="#">@Model.DisplayName</a>
                                    </div>
                                    <a href="#" class="tt-info-time">
                                        <i class="tt-icon"><svg><use xlink:href="#icon-time"></use></svg></i>@Model.CreatedOn
                                    </a>
                                </div>
                                <h3 class="tt-item-title">
                                    <a href="#">@Model.Title</a>
                                </h3>
                            </div>
                            <div class="tt-item-description">
                                <h6 class="tt-title">@Model.Content</h6>
                            </div>
                            <div class="tt-item-info info-bottom">
                                <a class="tt-icon-btn">
                                    <i class="tt-icon"><svg><use xlink:href="#icon-like"></use></svg></i>
                                    <span class="tt-text">@Model.Likes.Count</span>
                                </a>
                                <div class="col-separator"></div>
                                <a href=~/images/single-topic-img05.jpg class="tt-icon-btn tt-hover-02 tt-small-indent">
                                    <i class="tt-icon"><svg><use xlink:href="#icon-share"></use></svg></i>
                                </a>
                                <a href="#" class="tt-icon-btn tt-hover-02 tt-small-indent">
                                    <i class="tt-icon"><svg><use xlink:href="#icon-flag"></use></svg></i>
                                </a>
                                <a href="#" class="tt-icon-btn tt-hover-02 tt-small-indent">
                                    <i class="tt-icon"><svg><use xlink:href="#icon-reply"></use></svg></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @if (Model.Comments.Any())
        {
            @foreach (var item in Model.Comments)
            {

                <div class="tt-single-topic">
                    <div class="tt-item-header">
                        <div class="tt-item-info info-top">
                            <div class="tt-avatar-icon">
                                <i class="tt-icon"><svg><use xlink:href="#icon-ava-d"></use></svg></i>
                            </div>
                            <div class="tt-avatar-title">
                                <h6>@Model.DisplayName</h6>
                            </div>
                            <a href="#" class="tt-info-time">
                                <i class="tt-icon"><svg><use xlink:href="#icon-time"></use></svg></i>@item.CreatedOn
                            </a>
                        </div>
                        <h3 class="tt-item-title">
                            @Model.Title
                        </h3>
                    </div>
                    <div class="tt-item-description">
                        @item.Content<br>
                    </div>
                    <div class="tt-item-info info-bottom">
                        <a class="tt-icon-btn">
                            <i class="tt-icon"><svg><use xlink:href="#icon-like"></use></svg></i>
                            <span class="tt-text">@item.Likes.Count</span>
                        </a>
                        <div class="col-separator"></div>
                        <a href="#" class="tt-icon-btn tt-hover-02 tt-small-indent">
                            <i class="tt-icon"><svg><use xlink:href="#icon-share"></use></svg></i>
                        </a>
                        <a href="#" class="tt-icon-btn tt-hover-02 tt-small-indent">
                            <i class="tt-icon"><svg><use xlink:href="#icon-flag"></use></svg></i>
                        </a>
                        <a href="#" class="tt-icon-btn tt-hover-02 tt-small-indent">
                            <i class="tt-icon"><svg><use xlink:href="#icon-reply"></use></svg></i>
                        </a>
                    </div>
                </div>

            }
        }
        else
        {
            <p>"Be the first to comment"</p>
        }
        <div class="tt-wrapper-inner">
            <div class="pt-editor form-default">
                <h6 class="pt-title">Post your comment</h6>
                <div class="pt-row">
                    <div class="col-left">
                        <ul class="pt-edit-btn">
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-quote"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-bold"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-italic"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-share_topic"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-blockquote"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-performatted"></use>
                                    </svg>
                                </button>
                            </li>
                            <li class="hr"></li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-upload_files"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-bullet_list"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-heading"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-horizontal_line"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-emoticon"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-settings"></use>
                                    </svg>
                                </button>
                            </li>
                            <li>
                                <button type="button" class="btn-icon">
                                    <svg class="tt-icon">
                                        <use xlink:href="#icon-color_picker"></use>
                                    </svg>
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
                <form method="post" role="form" class="comment-form">
                    <div class="form-group">
                        <textarea maxlength="500" id="comment-message" asp-for="@Model.NewComment" class="form-control" rows="5" placeholder="Lets get started"></textarea>
                        <div class="col-auto"></div>
                    </div>
                    <div hidden="hidden">
                        <input asp-for="@Model.Id" value="@Model.Id" id="bar-id" />
                    </div>
                    <div class="col-md-12">
                        <button type="submit" asp-action="Create" asp-controller="Comment" class="btn btn-primary">Comment</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>